// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOKfNfofiuMUKgrZADzywczAYSur2Rjsw',
    appId: '1:520836257374:web:b49e3a92401707658886cf',
    messagingSenderId: '520836257374',
    projectId: 'crzycrypto-5e873',
    authDomain: 'crzycrypto-5e873.firebaseapp.com',
    storageBucket: 'crzycrypto-5e873.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbzcqTqxmGyVFxfS6e9heoQPpWrbVo0to',
    appId: '1:453462497977:android:1e54f30410d20e88c65968',
    messagingSenderId: '453462497977',
    projectId: 'fir-loginsignup-6cdbe',
    storageBucket: 'fir-loginsignup-6cdbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAr2mDzcF5LZMJGdE5spJ1QVFEygO65po',
    appId: '1:453462497977:ios:f8bbfccbb26d98c4c65968',
    messagingSenderId: '453462497977',
    projectId: 'fir-loginsignup-6cdbe',
    storageBucket: 'fir-loginsignup-6cdbe.firebasestorage.app',
    iosClientId: '453462497977-ba425m56ka1ncd0fm2pmm2kmsjb84c2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.crzyCrypto',
  );

}